/**
 * Root Lingui CLI configuration. `pnpm exec lingui extract` (wrapped by
 * `junius i18n extract`) walks the listed sources, looks for `t` / `Trans`
 * macro calls, and updates each package's `i18n/<locale>.po`.
 *
 * The catalog format mirrors what the backend codegen consumes: gettext `.po`,
 * key-based — msgid is a stable id supplied at the call site, msgstr is the
 * source-language template. So plugin authors use Lingui's explicit-id form:
 *
 *   t({ id: 'hello.page.greeting', message: 'Hello, {name}', values: { name } })
 *   <Trans id="hello.page.title">Hello</Trans>
 *
 * One [src/<loc>.po] per locale per package. `pseudo` is generated by Lingui
 * (`--clean --overwrite`) during the `junius i18n check` pseudo-pass.
 */
const locales = ['en', 'de', 'pseudo'];

/** Helper: one Lingui catalog entry per package, mirroring our backend layout. */
const pkg = (path) => ({
  path: `${path}/i18n/{locale}`,
  include: [`${path}/src`],
});

module.exports = {
  locales,
  sourceLocale: 'en',
  pseudoLocale: 'pseudo',
  format: 'po',
  catalogs: [
    pkg('platform/frontend'),
    pkg('plugins/hello/frontend'),
    pkg('plugins/greetings/frontend'),
    pkg('plugins/widgets/frontend'),
    pkg('plugins/events/frontend'),
  ],
};
