/**
 * Root Lingui CLI configuration. `pnpm exec lingui extract` (wrapped by
 * `junius i18n extract`) walks the listed sources, looks for `t` / `Trans`
 * macro calls, and updates each package's `i18n/<locale>.po`.
 *
 * The catalog format mirrors what the backend codegen consumes: gettext `.po`,
 * key-based — msgid is a stable id supplied at the call site, msgstr is the
 * source-language template. So plugin authors use Lingui's explicit-id form:
 *
 *   t({ id: 'hello.page.greeting', message: 'Hello, {name}', values: { name } })
 *   <Trans id="hello.page.title">Hello</Trans>
 *
 * One [src/<loc>.po] per locale per package. `pseudo` is generated by Lingui
 * (`--clean --overwrite`) during the `junius i18n check` pseudo-pass.
 *
 * NOTE on absolute paths: `@lingui/vite-plugin@5.9.5`'s catalog matcher
 * (`getCatalogForFile` → `path.relative(rootDir, catalogGlob)`) resolves
 * relative catalog paths against `process.cwd()` rather than against the
 * config's rootDir. When vite is invoked from a workspace subdir (e.g.
 * `pnpm --filter @junius/shell build` runs from `platform/frontend/`),
 * relative paths get a double-prefix and never match, breaking the embedded
 * build. Anchoring catalog paths at `__dirname` (the config-file directory)
 * makes them cwd-independent and avoids that footgun.
 */
const path = require('node:path');
const locales = ['en', 'de', 'pseudo'];
const ROOT = __dirname;

/** Helper: one Lingui catalog entry per package, mirroring our backend layout. */
const pkg = (relPath) => ({
  path: path.posix.join(ROOT, relPath, 'i18n/{locale}'),
  include: [path.posix.join(ROOT, relPath, 'src')],
});

module.exports = {
  locales,
  sourceLocale: 'en',
  pseudoLocale: 'pseudo',
  format: 'po',
  rootDir: ROOT,
  catalogs: [pkg('platform/frontend'), pkg('plugins/events/frontend')],
};
