//! Host-side RPC permission guard.
//!
//! A tower middleware on the `/rpc` subtree that enforces each method's
//! `option (platform.v1.requires)` *before* the plugin handler runs — the
//! defense-in-depth half of M07's RPC enforcement (the handler's typed
//! `Ctx<P>::from_rpc` is the other half). It reads the required permissions from
//! the [`RPC_REQUIRES`] table (generated by `junius sync`) and the caller from
//! request extensions (set by the session middleware), rejecting with a
//! Connect-shaped error before dispatch.

use axum::extract::Request;
use axum::middleware::Next;
use axum::response::{IntoResponse, Response};
use junius_sdk::{ApiError, User};

use crate::generated::rpc_requires::RPC_REQUIRES;

/// Look up a method's required permissions by its post-nest path
/// (`/<service>/<method>`). `None` = not annotated → no requirement.
fn required_permissions(path: &str) -> Option<&'static [&'static str]> {
    let (service, method) = path.strip_prefix('/')?.rsplit_once('/')?;
    RPC_REQUIRES
        .iter()
        .find(|(s, m, _)| *s == service && *m == method)
        .map(|(_, _, perms)| *perms)
}

/// Reject the request if the caller lacks any permission the method requires.
pub async fn require_permissions(req: Request, next: Next) -> Response {
    if let Some(perms) = required_permissions(req.uri().path()) {
        if !perms.is_empty() {
            match req.extensions().get::<User>() {
                None => return ApiError::unauthenticated().into_response(),
                Some(user) => {
                    for &perm in perms {
                        if !user.has_permission(perm) {
                            return ApiError::forbidden(perm).into_response();
                        }
                    }
                }
            }
        }
    }
    next.run(req).await
}
