//! Host-side RPC permission guard.
//!
//! A tower middleware on the `/rpc` subtree that enforces each method's
//! `option (platform.v1.requires)` *before* the plugin handler runs — the
//! defense-in-depth half of M07's RPC enforcement (the handler's typed
//! `Ctx<P>::from_rpc` is the other half). It reads the required permissions from
//! the [`RPC_REQUIRES`] table (generated by `junius sync`) and the caller from
//! request extensions (set by the session middleware), rejecting with a
//! Connect-shaped error before dispatch.

use std::collections::HashMap;
use std::sync::Arc;

use axum::extract::{Request, State};
use axum::middleware::Next;
use axum::response::{IntoResponse, Response};
use junius_sdk::{AdminAuth, ApiError, PluginResourceCtx, User};

use crate::generated::rpc_requires::{RPC_REQUIRES, RPC_SERVICES};

/// The plugin that owns the service at this post-nest path (`/<service>/<method>`).
fn plugin_for_path(path: &str) -> Option<&'static str> {
    let (service, _method) = path.strip_prefix('/')?.rsplit_once('/')?;
    RPC_SERVICES
        .iter()
        .find(|(s, _)| *s == service)
        .map(|(_, plugin)| *plugin)
}

/// Attach the owning plugin's `PluginResourceCtx` to the request, so the
/// aggregated `/rpc` router's handler reads *its* plugin's context via
/// `PluginContext::from_rpc`. (HTTP routes get this per-subtree; RPC shares one
/// router, so the right ctx is selected per request by service FQN.)
pub(crate) async fn inject_ctx(
    State(ctxs): State<Arc<HashMap<String, PluginResourceCtx>>>,
    mut req: Request,
    next: Next,
) -> Response {
    if let Some(plugin) = plugin_for_path(req.uri().path()) {
        if let Some(ctx) = ctxs.get(plugin) {
            req.extensions_mut().insert(ctx.clone());
        }
    }
    next.run(req).await
}

/// Look up a method's required permissions by its post-nest path
/// (`/<service>/<method>`). `None` = not annotated → no requirement.
fn required_permissions(path: &str) -> Option<&'static [&'static str]> {
    let (service, method) = path.strip_prefix('/')?.rsplit_once('/')?;
    RPC_REQUIRES
        .iter()
        .find(|(s, m, _)| *s == service && *m == method)
        .map(|(_, _, perms)| *perms)
}

/// Reject the request if the caller lacks any permission the method requires.
pub async fn require_permissions(req: Request, next: Next) -> Response {
    if let Some(perms) = required_permissions(req.uri().path()) {
        if !perms.is_empty() {
            match req.extensions().get::<User>() {
                None => return ApiError::unauthenticated().into_response(),
                Some(user) => {
                    for &perm in perms {
                        if !user.has_permission(perm) {
                            return ApiError::forbidden(perm).into_response();
                        }
                    }
                }
            }
        }
    }
    next.run(req).await
}

/// Admin-token gate for host-owned RPC methods (M18). When a request carries
/// `Authorization: Bearer <token>` matching the configured `admin_api_token`,
/// insert an [`AdminAuth`] marker so a host handler's `HostCtx::is_admin_token()`
/// returns true. An absent header, no configured token, or a mismatch inserts
/// nothing — a no-op for plugin RPC and for ordinary session callers. The token
/// comparison is constant-time.
pub(crate) async fn admin_token(
    State(expected): State<Option<Arc<str>>>,
    mut req: Request,
    next: Next,
) -> Response {
    if let Some(expected) = expected.as_deref() {
        if let Some(presented) = bearer_token(&req) {
            if constant_time_eq(presented.as_bytes(), expected.as_bytes()) {
                req.extensions_mut().insert(AdminAuth);
            }
        }
    }
    next.run(req).await
}

/// Extract a `Bearer <token>` value from the `Authorization` header.
fn bearer_token(req: &Request) -> Option<&str> {
    req.headers()
        .get(axum::http::header::AUTHORIZATION)?
        .to_str()
        .ok()?
        .strip_prefix("Bearer ")
}

/// Length-checked constant-time byte comparison (avoids leaking the match
/// position via early return). The length check itself can leak the token
/// length, which is not sensitive here.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn constant_time_eq_matches() {
        assert!(constant_time_eq(b"secret", b"secret"));
        assert!(!constant_time_eq(b"secret", b"secreT"));
        assert!(!constant_time_eq(b"secret", b"secret-longer"));
        assert!(!constant_time_eq(b"", b"x"));
    }

    #[test]
    fn path_resolves_to_owning_plugin() {
        // RPC_SERVICES is generated; events' services map to "events".
        assert_eq!(
            plugin_for_path("/events.v1.EventService/ListEvents"),
            Some("events")
        );
        assert_eq!(
            plugin_for_path("/events.v1.InviteService/ListSignups"),
            Some("events")
        );
        assert_eq!(plugin_for_path("/unknown.v1.Svc/M"), None);
        assert_eq!(plugin_for_path("/malformed"), None);
    }
}
