//! `events` — the events plugin (M13). The first real domain plugin: events that
//! belong to a **user or a group** and are **private or public**, with per-instance
//! access control (public events bypass the ACL on read; private ones are gated by
//! ownership/shares). Stage 6 shipped the event domain core (`EventService`);
//! Stage 7 adds invites + sign-ups (`InviteService`): owner-gated configuration
//! plus the **ungated** viewer surface (GetInvite/Signup/OptOut) whose access is
//! enforced at runtime by the event ACL rather than a compile-time witness.
//! iCalendar feeds and the confirmation-email job land in later stages.

use std::sync::Arc;

use async_trait::async_trait;
use axum::{Router, routing::get};
use connectrpc::{ConnectError, Encodable, RequestContext, Response, ServiceResult};
use junius_sdk::{
    EmailMessage, GroupId, Job, JobHandler, Plugin, PluginContext, PluginCtx, PluginError,
    PluginMetadata, PluginResources, Principal, UserId,
};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

junius_sdk::plugin_metadata!();

mod proto {
    //! Generated by `connectrpc-build` (see build.rs): buffa message types plus
    //! the `events.v1` Connect service traits + registration glue.
    #![allow(
        clippy::all,
        clippy::pedantic,
        missing_docs,
        dead_code,
        unused_qualifications
    )]
    include!(concat!(env!("OUT_DIR"), "/_connectrpc.rs"));
}

pub mod domain;
mod http;
pub mod ics;
pub mod repo;

use chrono::{DateTime, Utc};

use crate::domain::{EventId, FeedKind, OwnerKind, Visibility, generate_feed_key, hash_token};
use crate::permissions::{EventsRead, EventsShare, EventsWrite};
use crate::repo::{
    CalendarRepo, EventRepo, EventUpdate, EventView, Invite, InviteConfig, InvitePage, InviteRepo,
    NewEvent, SignupRepo, SignupRow, TokenInfo,
};
use junius_sdk::User;

use proto::events::v1 as pb;
use proto::events::v1::{
    CalendarService, CalendarServiceExt, EventService, EventServiceExt, InviteService,
    InviteServiceExt, OwnedCreateEventRequestView, OwnedCreateGroupKeyRequestView,
    OwnedCreateInviteRequestView, OwnedDeleteEventRequestView, OwnedGetEventRequestView,
    OwnedGetInviteRequestView, OwnedGetPersonalFeedRequestView, OwnedListEventsRequestView,
    OwnedListFeedsRequestView, OwnedListSignupsRequestView, OwnedOptOutRequestView,
    OwnedRevokeFeedRequestView, OwnedSetGroupPublicRequestView, OwnedShareEventRequestView,
    OwnedSignupRequestView, OwnedUpdateEventRequestView, OwnedUpdateInviteRequestView,
};

/// Per-request state for the events plugin: its repositories, typed on the
/// permission witness `P`. `#[derive(PluginCtx)]` generates the extractor.
#[derive(PluginCtx)]
pub struct EventState<P = ()> {
    #[repo]
    pub events: EventRepo<P>,
    #[repo]
    pub invites: InviteRepo<P>,
    #[repo]
    pub signups: SignupRepo<P>,
    #[repo]
    pub calendar: CalendarRepo<P>,
}

/// The events plugin's request context: state + caller + resources, proven to
/// hold the permissions in `P`.
pub type EventCtx<P = ()> = PluginContext<EventState<P>, P>;

pub struct EventsPlugin;

impl EventsPlugin {
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl Default for EventsPlugin {
    fn default() -> Self {
        Self::new()
    }
}

/// Connect-RPC implementation of `events.v1.EventService`. Each handler builds a
/// typed `EventCtx<P>` from the request context (`from_rpc`), which re-checks the
/// witness and yields the permission-gated repository; the host's RPC guard also
/// enforces each method's `(platform.v1.requires)` before the handler runs.
struct EventRpc;

impl EventService for EventRpc {
    async fn list_events(
        &self,
        ctx: RequestContext,
        _request: OwnedListEventsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListEventsResponse>> {
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead)>::from_rpc(&ctx)?;
        let events = ectx.state.events.list().await?;
        Ok(Response::new(pb::ListEventsResponse {
            events: events.into_iter().map(event_to_proto).collect(),
            ..Default::default()
        }))
    }

    async fn get_event(
        &self,
        ctx: RequestContext,
        request: OwnedGetEventRequestView,
    ) -> ServiceResult<impl Encodable<pb::GetEventResponse>> {
        let id = EventId(parse_uuid(request.id, "id")?);
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead)>::from_rpc(&ctx)?;
        let event = ectx.state.events.get(id).await?;
        Ok(Response::new(pb::GetEventResponse {
            event: Some(event_to_proto(event)).into(),
            ..Default::default()
        }))
    }

    async fn create_event(
        &self,
        ctx: RequestContext,
        request: OwnedCreateEventRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateEventResponse>> {
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead & EventsWrite)>::from_rpc(&ctx)?;
        let caller = ectx
            .user
            .as_ref()
            .map(|u| u.id)
            .ok_or_else(|| ConnectError::unauthenticated("authentication required"))?;
        // Resolve + authorize the owner: a user event is owned by the caller; a
        // group event requires the caller to belong to that group.
        let owner = match request.owner_kind {
            "user" | "" => Principal::User(caller),
            "group" => {
                let gid = GroupId(parse_uuid(request.owner_id, "owner_id")?);
                if !ectx.resources.groups.is_member(gid, caller).await? {
                    return Err(ConnectError::permission_denied(
                        "you must be a member of the owning group",
                    ));
                }
                Principal::Group(gid)
            }
            _ => {
                return Err(ConnectError::invalid_argument(
                    "owner_kind must be \"user\" or \"group\"",
                ));
            }
        };
        let new = NewEvent {
            title: require_nonempty(request.title, "title")?,
            description: optional(request.description),
            location: optional(request.location),
            starts_at: parse_rfc3339(request.starts_at, "starts_at")?,
            ends_at: parse_optional_rfc3339(request.ends_at)?,
            all_day: request.all_day,
            visibility: parse_visibility(request.visibility)?,
        };
        let created = ectx
            .state
            .events
            .create(new, owner, &ectx.resources.authz)
            .await?;
        Ok(Response::new(pb::CreateEventResponse {
            event: Some(event_to_proto(created)).into(),
            ..Default::default()
        }))
    }

    async fn update_event(
        &self,
        ctx: RequestContext,
        request: OwnedUpdateEventRequestView,
    ) -> ServiceResult<impl Encodable<pb::UpdateEventResponse>> {
        let id = EventId(parse_uuid(request.id, "id")?);
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead & EventsWrite)>::from_rpc(&ctx)?;
        let update = EventUpdate {
            title: require_nonempty(request.title, "title")?,
            description: optional(request.description),
            location: optional(request.location),
            starts_at: parse_rfc3339(request.starts_at, "starts_at")?,
            ends_at: parse_optional_rfc3339(request.ends_at)?,
            all_day: request.all_day,
            visibility: parse_visibility(request.visibility)?,
        };
        let updated = ectx.state.events.update(id, update).await?;
        Ok(Response::new(pb::UpdateEventResponse {
            event: Some(event_to_proto(updated)).into(),
            ..Default::default()
        }))
    }

    async fn delete_event(
        &self,
        ctx: RequestContext,
        request: OwnedDeleteEventRequestView,
    ) -> ServiceResult<impl Encodable<pb::DeleteEventResponse>> {
        let id = EventId(parse_uuid(request.id, "id")?);
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead & EventsWrite)>::from_rpc(&ctx)?;
        ectx.state.events.delete(id).await?;
        Ok(Response::new(pb::DeleteEventResponse::default()))
    }

    async fn share_event(
        &self,
        ctx: RequestContext,
        request: OwnedShareEventRequestView,
    ) -> ServiceResult<impl Encodable<pb::ShareEventResponse>> {
        let event_id = parse_uuid(request.id, "id")?;
        let principal = parse_principal(request.principal_kind, request.principal_id)?;
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead & EventsShare)>::from_rpc(&ctx)?;
        let share = ectx
            .resources
            .authz
            .share(
                "events:event",
                event_id,
                principal,
                request.permission,
                None,
            )
            .await?;
        Ok(Response::new(pb::ShareEventResponse {
            share_id: share.id.to_string(),
            ..Default::default()
        }))
    }
}

/// Convert an event view (with the viewer's server-computed flags) into proto.
fn event_to_proto(e: EventView) -> pb::Event {
    let (owner_kind, owner_id) = match e.owner_kind {
        OwnerKind::User => ("user", e.owning_user_id),
        OwnerKind::Group => ("group", e.owning_group_id),
    };
    let visibility = match e.visibility {
        Visibility::Private => "private",
        Visibility::Public => "public",
    };
    pb::Event {
        id: e.id.to_string(),
        title: e.title,
        description: e.description.unwrap_or_default(),
        location: e.location.unwrap_or_default(),
        starts_at: e.starts_at.to_rfc3339(),
        ends_at: e.ends_at.map(|t| t.to_rfc3339()).unwrap_or_default(),
        all_day: e.all_day,
        visibility: visibility.to_string(),
        owner_kind: owner_kind.to_string(),
        owner_id: owner_id.map(|u| u.to_string()).unwrap_or_default(),
        viewer_can_edit: e.viewer_can_edit,
        viewer_can_share: e.viewer_can_share,
        ..Default::default()
    }
}

/// Parse a UUID request field, mapping a parse failure to `invalid_argument`.
fn parse_uuid(value: &str, field: &str) -> Result<Uuid, ConnectError> {
    Uuid::parse_str(value).map_err(|_| ConnectError::invalid_argument(format!("invalid {field}")))
}

/// An empty proto string field becomes `None`; anything else `Some`.
fn optional(value: &str) -> Option<String> {
    if value.is_empty() {
        None
    } else {
        Some(value.to_string())
    }
}

/// Require a non-empty (after trim) string field.
fn require_nonempty(value: &str, field: &str) -> Result<String, ConnectError> {
    if value.trim().is_empty() {
        Err(ConnectError::invalid_argument(format!(
            "{field} is required"
        )))
    } else {
        Ok(value.to_string())
    }
}

/// Parse an RFC 3339 timestamp request field.
fn parse_rfc3339(value: &str, field: &str) -> Result<DateTime<Utc>, ConnectError> {
    DateTime::parse_from_rfc3339(value)
        .map(|d| d.with_timezone(&Utc))
        .map_err(|_| ConnectError::invalid_argument(format!("invalid {field} (expected RFC 3339)")))
}

/// Parse an optional RFC 3339 timestamp: empty → `None`.
fn parse_optional_rfc3339(value: &str) -> Result<Option<DateTime<Utc>>, ConnectError> {
    if value.is_empty() {
        Ok(None)
    } else {
        Ok(Some(parse_rfc3339(value, "ends_at")?))
    }
}

/// Parse a visibility request field; empty defaults to `private`.
fn parse_visibility(value: &str) -> Result<Visibility, ConnectError> {
    match value {
        "public" => Ok(Visibility::Public),
        "private" | "" => Ok(Visibility::Private),
        _ => Err(ConnectError::invalid_argument(
            "visibility must be \"private\" or \"public\"",
        )),
    }
}

/// Parse a `(principal_kind, principal_id)` pair from a `ShareEvent` request.
fn parse_principal(kind: &str, id: &str) -> Result<Principal, ConnectError> {
    match kind {
        "user" => Ok(Principal::User(UserId(parse_uuid(id, "principal_id")?))),
        "group" => Ok(Principal::Group(GroupId(parse_uuid(id, "principal_id")?))),
        "public" => Ok(Principal::Public),
        _ => Err(ConnectError::invalid_argument(
            "principal_kind must be user, group, or public",
        )),
    }
}

/// Connect-RPC implementation of `events.v1.InviteService`. Owner-side methods
/// build a permission-gated `EventCtx<P>`; the viewer-side methods build the
/// **no-witness** `EventCtx<()>` (so anonymous callers reach them) and rely on
/// the repository's runtime ACL.
struct InviteRpc;

impl InviteService for InviteRpc {
    async fn create_invite(
        &self,
        ctx: RequestContext,
        request: OwnedCreateInviteRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateInviteResponse>> {
        let event_id = parse_uuid(request.event_id, "event_id")?;
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead & EventsWrite)>::from_rpc(&ctx)?;
        let caller = ectx
            .user
            .as_ref()
            .map(|u| u.id)
            .ok_or_else(|| ConnectError::unauthenticated("authentication required"))?;
        // Fetch the event (also confirms read access + gives the owner) before
        // creating its invite.
        let event = ectx.state.events.get(EventId(event_id)).await?;
        let config = InviteConfig {
            signup_enabled: request.signup_enabled,
            signup_open: request.signup_open,
            slot_limit: (request.slot_limit > 0).then_some(request.slot_limit),
            show_title: request.show_title,
            show_datetime: request.show_datetime,
            show_location: request.show_location,
            show_description: request.show_description,
            show_remaining: request.show_remaining,
        };
        let slug = crate::domain::generate_slug();
        let invite = match ectx.state.invites.create(event_id, &slug, &config).await {
            Ok(invite) => invite,
            Err(junius_sdk::RepoError::Db(e)) if is_unique_violation(&e) => {
                return Err(ConnectError::already_exists(
                    "an invite already exists for this event",
                ));
            }
            Err(e) => return Err(e.into()),
        };
        // Group pre-sign-up: snapshot the owning group's current members as going.
        if request.presignup_group && matches!(event.owner_kind, OwnerKind::Group) {
            if let Some(gid) = event.owning_group_id {
                let members = ectx.resources.groups.members(GroupId(gid), caller).await?;
                let ids: Vec<UserId> = members.into_iter().map(|m| m.user.id).collect();
                ectx.state.signups.presign_users(invite.id, &ids).await?;
            }
        }
        Ok(Response::new(pb::CreateInviteResponse {
            invite: Some(invite_to_proto(invite)).into(),
            ..Default::default()
        }))
    }

    async fn update_invite(
        &self,
        ctx: RequestContext,
        request: OwnedUpdateInviteRequestView,
    ) -> ServiceResult<impl Encodable<pb::UpdateInviteResponse>> {
        let event_id = parse_uuid(request.event_id, "event_id")?;
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead & EventsWrite)>::from_rpc(&ctx)?;
        let config = InviteConfig {
            signup_enabled: request.signup_enabled,
            signup_open: request.signup_open,
            slot_limit: (request.slot_limit > 0).then_some(request.slot_limit),
            show_title: request.show_title,
            show_datetime: request.show_datetime,
            show_location: request.show_location,
            show_description: request.show_description,
            show_remaining: request.show_remaining,
        };
        let invite = ectx.state.invites.update(event_id, &config).await?;
        Ok(Response::new(pb::UpdateInviteResponse {
            invite: Some(invite_to_proto(invite)).into(),
            ..Default::default()
        }))
    }

    async fn list_signups(
        &self,
        ctx: RequestContext,
        request: OwnedListSignupsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListSignupsResponse>> {
        let event_id = parse_uuid(request.event_id, "event_id")?;
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead)>::from_rpc(&ctx)?;
        let rows = ectx.state.invites.list_signups(event_id).await?;
        let mut signups = Vec::with_capacity(rows.len());
        for row in rows {
            // Resolve a display name/email for user sign-ups via the directory;
            // guests carry their own.
            let (display_name, email) = match row.user_id {
                Some(uid) => ectx
                    .resources
                    .users
                    .lookup(UserId(uid))
                    .await?
                    .map(|u| (u.display_name, u.email))
                    .unwrap_or_default(),
                None => (
                    row.guest_name.clone().unwrap_or_default(),
                    row.guest_email.clone().unwrap_or_default(),
                ),
            };
            signups.push(signup_to_proto(&row, display_name, email));
        }
        Ok(Response::new(pb::ListSignupsResponse {
            signups,
            ..Default::default()
        }))
    }

    async fn get_invite(
        &self,
        ctx: RequestContext,
        request: OwnedGetInviteRequestView,
    ) -> ServiceResult<impl Encodable<pb::GetInviteResponse>> {
        // No witness: anonymous callers reach this; the repo enforces the ACL.
        let ectx = EventCtx::<()>::from_rpc(&ctx)?;
        let page = ectx.state.invites.get_page_by_slug(request.slug).await?;
        Ok(Response::new(invite_page_to_proto(page)))
    }

    async fn signup(
        &self,
        ctx: RequestContext,
        request: OwnedSignupRequestView,
    ) -> ServiceResult<impl Encodable<pb::SignupResponse>> {
        let ectx = EventCtx::<()>::from_rpc(&ctx)?;
        let outcome = ectx
            .state
            .signups
            .signup(
                request.slug,
                nonempty(request.guest_name),
                nonempty(request.guest_email),
            )
            .await?;
        // Recipient: a logged-in caller uses their directory identity; a guest the
        // submitted fields. Enqueue the confirmation best-effort — a missing job
        // backend must not fail the sign-up.
        let (recipient_email, recipient_name) = match ectx.user.as_ref() {
            Some(u) => (u.email.clone(), u.display_name.clone()),
            None => (
                request.guest_email.to_string(),
                request.guest_name.to_string(),
            ),
        };
        if !recipient_email.is_empty() {
            let job = SendSignupConfirmation {
                signup_id: outcome.id.to_string(),
                event_title: outcome.event_title.clone(),
                recipient_email,
                recipient_name,
            };
            if let Err(e) = ectx.resources.jobs.enqueue(job).await {
                tracing::warn!(error = %e, "failed to enqueue events.send_signup_confirmation");
            }
        }
        Ok(Response::new(pb::SignupResponse {
            signup_id: outcome.id.to_string(),
            status: outcome.status.as_str().to_string(),
            ..Default::default()
        }))
    }

    async fn opt_out(
        &self,
        ctx: RequestContext,
        request: OwnedOptOutRequestView,
    ) -> ServiceResult<impl Encodable<pb::OptOutResponse>> {
        let ectx = EventCtx::<()>::from_rpc(&ctx)?;
        ectx.state.signups.opt_out(request.slug).await?;
        Ok(Response::new(pb::OptOutResponse::default()))
    }
}

/// Convert an owner's invite view into proto (`slot_limit` 0 = unlimited).
fn invite_to_proto(i: Invite) -> pb::Invite {
    pb::Invite {
        id: i.id.to_string(),
        event_id: i.event_id.to_string(),
        slug: i.slug,
        signup_enabled: i.signup_enabled,
        signup_open: i.signup_open,
        slot_limit: i.slot_limit.unwrap_or(0),
        show_title: i.show_title,
        show_datetime: i.show_datetime,
        show_location: i.show_location,
        show_description: i.show_description,
        show_remaining: i.show_remaining,
        ..Default::default()
    }
}

/// Convert a sign-up row into proto, with the resolved display name + email.
fn signup_to_proto(row: &SignupRow, display_name: String, email: String) -> pb::Signup {
    pb::Signup {
        id: row.id.to_string(),
        kind: row.kind.as_str().to_string(),
        user_id: row.user_id.map(|u| u.to_string()).unwrap_or_default(),
        display_name,
        email,
        status: row.status.as_str().to_string(),
        created_at: row.created_at.to_rfc3339(),
        ..Default::default()
    }
}

/// Project the public invite page to proto, applying the `show_*` toggles so
/// hidden fields never leave the server, and computing the slot affordances.
fn invite_page_to_proto(p: InvitePage) -> pb::GetInviteResponse {
    let unlimited = p.slot_limit.is_none();
    let remaining = p.slot_limit.map_or(0, |limit| {
        let used = i32::try_from(p.going_count).unwrap_or(i32::MAX);
        limit.saturating_sub(used).max(0)
    });
    let can_signup = p.signup_enabled && p.signup_open && (unlimited || remaining > 0);
    pb::GetInviteResponse {
        slug: p.slug,
        event_id: p.event_id.to_string(),
        signup_enabled: p.signup_enabled,
        signup_open: p.signup_open,
        can_signup,
        show_remaining: p.show_remaining,
        unlimited_slots: unlimited,
        slots_remaining: if p.show_remaining && !unlimited {
            remaining
        } else {
            0
        },
        title: toggled(p.show_title, p.title),
        description: toggled(p.show_description, p.description.unwrap_or_default()),
        location: toggled(p.show_location, p.location.unwrap_or_default()),
        starts_at: toggled(p.show_datetime, p.starts_at.to_rfc3339()),
        ends_at: toggled(
            p.show_datetime,
            p.ends_at.map(|t| t.to_rfc3339()).unwrap_or_default(),
        ),
        all_day: p.show_datetime && p.all_day,
        ..Default::default()
    }
}

/// Return `value` only when `shown`, else the empty string (hidden field).
fn toggled(shown: bool, value: String) -> String {
    if shown { value } else { String::new() }
}

/// A non-empty trimmed view of a proto string field, else `None`.
fn nonempty(value: &str) -> Option<&str> {
    let trimmed = value.trim();
    (!trimmed.is_empty()).then_some(trimmed)
}

/// Whether a sqlx error is a unique-constraint violation.
fn is_unique_violation(e: &sqlx::Error) -> bool {
    e.as_database_error()
        .is_some_and(sqlx::error::DatabaseError::is_unique_violation)
}

/// Connect-RPC implementation of `events.v1.CalendarService`. Mints / lists /
/// revokes feed tokens and toggles a group's public calendar; the `.ics` feeds
/// these point at are served unauthenticated by [`crate::http`]. Group actions
/// additionally require the caller to hold `events:write` *within* the group.
struct CalendarRpc;

impl CalendarService for CalendarRpc {
    async fn get_personal_feed(
        &self,
        ctx: RequestContext,
        _request: OwnedGetPersonalFeedRequestView,
    ) -> ServiceResult<impl Encodable<pb::GetPersonalFeedResponse>> {
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead)>::from_rpc(&ctx)?;
        let caller = require_caller(ectx.user.as_ref())?;
        // Keys are stored hashed (not recoverable), so each call mints a fresh
        // personal key; old ones remain valid until revoked.
        let key = generate_feed_key();
        ectx.state
            .calendar
            .mint_token(
                FeedKind::Personal,
                Some(caller.0),
                None,
                caller.0,
                None,
                &hash_token(&key),
            )
            .await?;
        Ok(Response::new(pb::GetPersonalFeedResponse {
            url: format!("/h/events/ics/u/{key}"),
            ..Default::default()
        }))
    }

    async fn create_group_key(
        &self,
        ctx: RequestContext,
        request: OwnedCreateGroupKeyRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateGroupKeyResponse>> {
        let group_id = parse_uuid(request.group_id, "group_id")?;
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead & EventsWrite)>::from_rpc(&ctx)?;
        let caller = require_user(ectx.user.as_ref())?;
        require_group_write(caller, group_id)?;
        let key = generate_feed_key();
        ectx.state
            .calendar
            .mint_token(
                FeedKind::Group,
                None,
                Some(group_id),
                caller.id.0,
                nonempty(request.label),
                &hash_token(&key),
            )
            .await?;
        let name = ectx
            .resources
            .groups
            .by_id(GroupId(group_id))
            .await?
            .map_or_else(|| group_id.to_string(), |g| encode_segment(&g.name));
        Ok(Response::new(pb::CreateGroupKeyResponse {
            url: format!("/h/events/ics/g/{name}/{key}"),
            ..Default::default()
        }))
    }

    async fn set_group_public(
        &self,
        ctx: RequestContext,
        request: OwnedSetGroupPublicRequestView,
    ) -> ServiceResult<impl Encodable<pb::SetGroupPublicResponse>> {
        let group_id = parse_uuid(request.group_id, "group_id")?;
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead & EventsWrite)>::from_rpc(&ctx)?;
        let caller = require_user(ectx.user.as_ref())?;
        require_group_write(caller, group_id)?;
        ectx.state
            .calendar
            .set_group_public(group_id, request.public, caller.id.0)
            .await?;
        Ok(Response::new(pb::SetGroupPublicResponse::default()))
    }

    async fn list_feeds(
        &self,
        ctx: RequestContext,
        _request: OwnedListFeedsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListFeedsResponse>> {
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead)>::from_rpc(&ctx)?;
        let caller = require_caller(ectx.user.as_ref())?;
        let tokens = ectx.state.calendar.list_tokens(caller.0).await?;
        Ok(Response::new(pb::ListFeedsResponse {
            feeds: tokens.into_iter().map(feed_to_proto).collect(),
            ..Default::default()
        }))
    }

    async fn revoke_feed(
        &self,
        ctx: RequestContext,
        request: OwnedRevokeFeedRequestView,
    ) -> ServiceResult<impl Encodable<pb::RevokeFeedResponse>> {
        let token_id = parse_uuid(request.id, "id")?;
        let ectx = EventCtx::<junius_sdk::permissions!(EventsRead)>::from_rpc(&ctx)?;
        let caller = require_caller(ectx.user.as_ref())?;
        ectx.state.calendar.revoke_token(token_id, caller.0).await?;
        Ok(Response::new(pb::RevokeFeedResponse::default()))
    }
}

/// The authenticated caller's id, or `unauthenticated` (gated methods should
/// always have one, but be defensive).
fn require_caller(user: Option<&User>) -> Result<UserId, ConnectError> {
    Ok(require_user(user)?.id)
}

/// The authenticated caller, or `unauthenticated`.
fn require_user(user: Option<&User>) -> Result<&User, ConnectError> {
    user.ok_or_else(|| ConnectError::unauthenticated("authentication required"))
}

/// Require the caller to hold `events:write` within `group_id` (a role in that
/// group granting it), beyond the static `events:write`-anywhere RPC gate.
fn require_group_write(caller: &User, group_id: Uuid) -> Result<(), ConnectError> {
    let ok = caller
        .memberships
        .iter()
        .any(|m| m.group_id.0 == group_id && m.permissions.contains("events:write"));
    if ok {
        Ok(())
    } else {
        Err(ConnectError::permission_denied(
            "you need events:write within this group",
        ))
    }
}

/// Convert a feed token into proto.
fn feed_to_proto(t: TokenInfo) -> pb::Feed {
    pb::Feed {
        id: t.id.to_string(),
        kind: match t.kind {
            FeedKind::Personal => "personal",
            FeedKind::Group => "group",
        }
        .to_string(),
        group_id: t
            .subject_group_id
            .map(|g| g.to_string())
            .unwrap_or_default(),
        label: t.label.unwrap_or_default(),
        created_at: t.created_at.to_rfc3339(),
        revoked: t.revoked,
        ..Default::default()
    }
}

/// Percent-encode a single URL path segment (group name in a feed URL is
/// cosmetic — the key is the credential — but the URL must still be valid).
fn encode_segment(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for byte in s.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char);
            }
            other => {
                use std::fmt::Write;
                let _ = write!(out, "%{other:02X}");
            }
        }
    }
    out
}

/// Background job (M10): email a sign-up confirmation. Enqueued by the `Signup`
/// handler; run out-of-band by the host job worker, which sends it via the gated
/// `email.send` capability.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SendSignupConfirmation {
    pub signup_id: String,
    pub event_title: String,
    pub recipient_email: String,
    pub recipient_name: String,
}

impl Job for SendSignupConfirmation {
    const NAME: &'static str = "events.send_signup_confirmation";
}

/// Handler for [`SendSignupConfirmation`] — runs in the worker with the plugin's
/// own resources, emailing the attendee via the gated `email.send` capability.
async fn send_signup_confirmation_handler(
    job: SendSignupConfirmation,
    resources: PluginResources,
) -> Result<(), PluginError> {
    let name = if job.recipient_name.trim().is_empty() {
        "there"
    } else {
        job.recipient_name.trim()
    };
    resources
        .email
        .send(EmailMessage {
            to: vec![job.recipient_email],
            subject: format!("You're signed up: {}", job.event_title),
            body_text: format!(
                "Hi {name},\n\nYou're confirmed for \"{}\".\n\nSee you there!",
                job.event_title
            ),
            ..Default::default()
        })
        .await
}

#[async_trait]
impl Plugin for EventsPlugin {
    fn metadata(&self) -> &'static PluginMetadata {
        &METADATA
    }

    fn routes(&self) -> Router {
        Router::new()
            .route("/ping", get(|| async { "pong" }))
            .merge(http::routes())
    }

    fn register_rpc(&self, router: connectrpc::Router) -> connectrpc::Router {
        let router = Arc::new(EventRpc).register(router);
        let router = Arc::new(InviteRpc).register(router);
        Arc::new(CalendarRpc).register(router)
    }

    fn jobs(&self) -> Vec<JobHandler> {
        vec![JobHandler::new::<SendSignupConfirmation, _, _>(
            send_signup_confirmation_handler,
        )]
    }
}
