//! `events` — the events plugin (M13). Stage 1 establishes the plugin shape: a
//! plain `GET /ping` HTTP route and a permission-free Connect `Ping` RPC, plus
//! the `events` schema + `event` table (migrations). The domain surface (event
//! CRUD with user/group ownership + visibility, invites, sign-ups, iCalendar
//! feeds) lands in later stages.

use std::sync::Arc;

use async_trait::async_trait;
use axum::{Router, routing::get};
use connectrpc::{Encodable, RequestContext, Response, ServiceResult};
use junius_sdk::{Plugin, PluginMetadata};

junius_sdk::plugin_metadata!();

mod proto {
    //! Generated by `connectrpc-build` (see build.rs): buffa message types plus
    //! the `events.v1` Connect service traits + registration glue.
    #![allow(
        clippy::all,
        clippy::pedantic,
        missing_docs,
        dead_code,
        unused_qualifications
    )]
    include!(concat!(env!("OUT_DIR"), "/_connectrpc.rs"));
}

use proto::events::v1::{EventService, EventServiceExt, OwnedPingRequestView, PingResponse};

pub struct EventsPlugin;

impl EventsPlugin {
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl Default for EventsPlugin {
    fn default() -> Self {
        Self::new()
    }
}

/// Connect-RPC service marker. Stage 1 exposes only the permission-free `Ping`.
struct EventRpc;

impl EventService for EventRpc {
    async fn ping(
        &self,
        _ctx: RequestContext,
        _request: OwnedPingRequestView,
    ) -> ServiceResult<impl Encodable<PingResponse>> {
        Ok(Response::new(PingResponse {
            message: "events ok".to_string(),
            ..Default::default()
        }))
    }
}

#[async_trait]
impl Plugin for EventsPlugin {
    fn metadata(&self) -> &'static PluginMetadata {
        &METADATA
    }

    fn routes(&self) -> Router {
        Router::new().route("/ping", get(|| async { "pong" }))
    }

    fn register_rpc(&self, router: connectrpc::Router) -> connectrpc::Router {
        Arc::new(EventRpc).register(router)
    }
}
