//! `greetings` — the M09 cross-plugin consumer. It depends on `hello` (required:
//! reads `hello.greeting_template` via SQL, calls `HelloService.Greet` from the
//! FE) and `widgets` (optional: consumes its `VenuePicker` component). The
//! backend stores greetings built from a hello template; the host folds this
//! plugin's `GreetingService` into the shared `/rpc` router alongside hello's.

use std::sync::Arc;

use async_trait::async_trait;
use axum::{Router, routing::get};
use connectrpc::{Encodable, RequestContext, Response, ServiceResult};
use junius_sdk::{Plugin, PluginContext, PluginCtx, PluginMetadata};

junius_sdk::plugin_metadata!();

mod proto {
    //! Generated by `connectrpc-build` (see build.rs): buffa message types plus
    //! the `GreetingService` Connect trait + registration glue.
    #![allow(
        clippy::all,
        clippy::pedantic,
        missing_docs,
        dead_code,
        unused_qualifications
    )]
    include!(concat!(env!("OUT_DIR"), "/_connectrpc.rs"));
}

pub mod repo;

use proto::greetings::v1 as pb;
use proto::greetings::v1::{
    GreetingService, GreetingServiceExt, OwnedCreateGreetingRequestView,
    OwnedListGreetingsRequestView,
};

use crate::permissions::{GreetingsRead, GreetingsWrite};
use crate::repo::{Greeting, GreetingRepo, NewGreeting};

/// Convert a stored greeting into its proto wire form (empty `venue` when none).
fn greeting_to_proto(g: Greeting) -> pb::Greeting {
    pb::Greeting {
        id: g.id.0.to_string(),
        template_id: g.template_id.to_string(),
        template_name: g.template_name,
        recipient: g.recipient,
        venue: g.venue.unwrap_or_default(),
        message: g.message,
        created: g.created.to_rfc3339(),
        ..Default::default()
    }
}

/// Per-request state for the greetings plugin: its repository, typed on the
/// permission witness `P`.
#[derive(PluginCtx)]
pub struct GreetingState<P = ()> {
    #[repo]
    pub greetings: GreetingRepo<P>,
}

/// The greetings plugin's request context: state + caller + resources, proven to
/// hold the permissions in `P`.
pub type GreetingCtx<P = ()> = PluginContext<GreetingState<P>, P>;

pub struct GreetingsPlugin;

impl GreetingsPlugin {
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl Default for GreetingsPlugin {
    fn default() -> Self {
        Self::new()
    }
}

/// Connect-RPC implementation of `greetings.v1.GreetingService`. Both methods
/// build a typed `GreetingCtx<P>` from the request context (`from_rpc`), which
/// re-checks the witness and yields the permission-gated repository. The host's
/// RPC guard also enforces each method's `(platform.v1.requires)` before dispatch.
struct GreetingRpc;

impl GreetingService for GreetingRpc {
    async fn list_greetings(
        &self,
        ctx: RequestContext,
        _request: OwnedListGreetingsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListGreetingsResponse>> {
        let gctx = GreetingCtx::<junius_sdk::permissions!(GreetingsRead)>::from_rpc(&ctx)?;
        let greetings = gctx.state.greetings.list().await?;
        Ok(Response::new(pb::ListGreetingsResponse {
            greetings: greetings.into_iter().map(greeting_to_proto).collect(),
            ..Default::default()
        }))
    }

    async fn create_greeting(
        &self,
        ctx: RequestContext,
        request: OwnedCreateGreetingRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateGreetingResponse>> {
        // An empty/unknown template_name resolves to no row → RepoError::NotFound.
        let venue = (!request.venue.is_empty()).then(|| request.venue.to_string());
        let gctx =
            GreetingCtx::<junius_sdk::permissions!(GreetingsRead & GreetingsWrite)>::from_rpc(
                &ctx,
            )?;
        let created = gctx
            .state
            .greetings
            .create(NewGreeting {
                template_name: request.template_name.to_string(),
                recipient: request.recipient.to_string(),
                venue,
            })
            .await?;
        Ok(Response::new(pb::CreateGreetingResponse {
            greeting: Some(greeting_to_proto(created)).into(),
            ..Default::default()
        }))
    }
}

#[async_trait]
impl Plugin for GreetingsPlugin {
    fn metadata(&self) -> &'static PluginMetadata {
        &METADATA
    }

    fn routes(&self) -> Router {
        Router::new().route("/ping", get(|| async { "pong" }))
    }

    fn register_rpc(&self, router: connectrpc::Router) -> connectrpc::Router {
        Arc::new(GreetingRpc).register(router)
    }
}
