//! Compile-time typed permission system.
//!
//! Each plugin's `plugin_metadata!()` expansion emits one zero-sized marker type
//! per declared `[permissions]` key (e.g. `permissions::HelloRead`) implementing
//! [`Permission`]. A *permission witness* `P` is a right-nested [`And`] chain
//! terminated by `()` — produced by the [`permissions!`](crate::permissions)
//! macro (`permissions!(A & B)` → `And<A, And<B, ()>>`). The empty witness `()`
//! proves nothing.
//!
//! Two things consume a witness:
//! - **Compile-time gating** via the [`Has<X>`] bound: a repository method on
//!   `impl<P: Has<HelloWrite>> HelloRepo<P>` is callable only when `P` contains
//!   `HelloWrite`. Membership is decided by the sealed, index-disambiguated
//!   [`Contains`] trait (the classic HList-membership encoding — distinct index
//!   witnesses keep the recursive impls from overlapping).
//! - **Runtime checking** via [`PermissionList::names`], which the `PluginCtx`
//!   extractor iterates to verify the caller actually holds each permission.

use core::marker::PhantomData;

/// A declared permission. One zero-sized marker type per `[permissions]` key is
/// generated by `plugin_metadata!()`; referencing an undeclared permission is a
/// compile error because the marker type doesn't exist.
pub trait Permission: Send + Sync + 'static {
    /// The wire/manifest name, e.g. `"hello:read"`.
    const NAME: &'static str;
}

/// Type-level conjunction. Witnesses are right-nested `And` chains terminated by
/// `()`: `And<A, And<B, ()>>`.
pub struct And<A, B>(PhantomData<(A, B)>);

mod sealed {
    pub trait Sealed {}
    impl<A, B> Sealed for super::And<A, B> {}
}

/// Index witness: the head of the chain holds the permission.
pub struct Here;
/// Index witness: the permission is somewhere in the tail.
pub struct There<T>(PhantomData<T>);

/// `Self` proves it holds permission `X`. `Idx` records *where* in the chain the
/// permission sits, so the head and tail impls carry different index types and
/// therefore don't overlap (the classic HList-membership encoding; without the
/// index, stable Rust rejects the recursive impls as conflicting). The index is
/// always inferable, so call sites pass `_` for it — and the
/// `#[impl_repository]` attribute injects a fresh index param for every
/// `Has<Perm>` bound an author writes, so repository impls read simply as
/// `impl<P: Has<HelloRead>> …`. Sealed: only the `And`-chain impls below exist.
pub trait Has<X, Idx>: sealed::Sealed {}

// Head: the permission is the chain's head.
impl<X: Permission, Tail> Has<X, Here> for And<X, Tail> {}
// Tail: recurse into the rest of the chain.
impl<Head, Tail, X, I> Has<X, There<I>> for And<Head, Tail> where Tail: Has<X, I> {}

/// Runtime enumeration of a witness's permission names, for the `PluginCtx`
/// extractor's caller check. `()` is empty; an `And` chain lists head-first.
pub trait PermissionList {
    /// The permission names this witness asserts.
    fn names() -> Vec<&'static str>;
}

impl PermissionList for () {
    fn names() -> Vec<&'static str> {
        Vec::new()
    }
}

impl<Head: Permission, Tail: PermissionList> PermissionList for And<Head, Tail> {
    fn names() -> Vec<&'static str> {
        let mut names = Tail::names();
        names.insert(0, Head::NAME);
        names
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    struct Read;
    impl Permission for Read {
        const NAME: &'static str = "demo:read";
    }
    struct Write;
    impl Permission for Write {
        const NAME: &'static str = "demo:write";
    }
    struct Admin;
    impl Permission for Admin {
        const NAME: &'static str = "demo:admin";
    }

    // Witnesses, as the `permissions!` macro would build them.
    type R = And<Read, ()>;
    type RW = And<Read, And<Write, ()>>;
    type Rwa = And<Read, And<Write, And<Admin, ()>>>;

    // `assert_has` only compiles if `P: Has<X, _>` (index inferred).
    fn assert_has<P: Has<X, I>, X, I>() {}

    #[test]
    fn membership_head_and_tail() {
        assert_has::<R, Read, _>();
        assert_has::<RW, Read, _>();
        assert_has::<RW, Write, _>();
        assert_has::<Rwa, Read, _>();
        assert_has::<Rwa, Write, _>();
        assert_has::<Rwa, Admin, _>(); // deep tail
    }

    #[test]
    fn permission_list_order_and_empty() {
        assert!(<()>::names().is_empty());
        assert_eq!(R::names(), vec!["demo:read"]);
        assert_eq!(RW::names(), vec!["demo:read", "demo:write"]);
        assert_eq!(Rwa::names(), vec!["demo:read", "demo:write", "demo:admin"]);
    }
}
