//! Host-owned Connect-RPC services (M18).
//!
//! The platform hosts `user.v1.UserService` directly — the first Connect
//! service that isn't a plugin's — to carry the off-login OIDC-group refresh
//! triggers. The generated message types + service trait come from `build.rs`
//! (`connectrpc-build`); the per-method permission-witness aliases come from
//! `junius-rpc-meta`. See [`user_service`] for the implementation.

pub mod proto {
    //! Generated by `connectrpc-build` (see `platform/build.rs`): the `user.v1`
    //! buffa message types + the Connect service trait + registration glue.
    #![allow(
        clippy::all,
        clippy::pedantic,
        missing_docs,
        dead_code,
        unused_qualifications
    )]
    include!(concat!(env!("OUT_DIR"), "/_connectrpc.rs"));
}

include!(concat!(env!("OUT_DIR"), "/_rpc_requires.rs"));

pub mod user_service;
