//! `admin` plugin (M18 Stage 2). Provides the platform's management surface:
//! groups, group-roles, group memberships, user-roles, user-role assignments,
//! and a read-only permission catalogue.
//!
//! Every mutation goes through `ctx.resources.platform_admin` — the typed
//! [`junius_sdk::PlatformAdminApi`] accessor — which runs on the platform
//! pool (plugins have no SELECT/INSERT on `platform.group*`/`user_role*`) and
//! audit-emits every change. The accessor is itself gated on the
//! `platform.admin` capability declared in this plugin's `plugin.toml`; the
//! host's trusted-capability allowlist additionally refuses to boot if any
//! other plugin declares the capability.
//!
//! Static RPC permission gating is via each method's
//! `option (platform.v1.requires)` annotation in `proto/admin/v1/admin.proto`.
//! The built-in `admin` user-role's wildcard (`*`) passes every gate
//! transparently; admins do not need explicit `admin:groups.read` etc. grants.

use std::sync::Arc;

use async_trait::async_trait;
use axum::{Router, routing::get};
use connectrpc::{ConnectError, Encodable, Response, ServiceResult};
use junius_sdk::{
    BuildState, GroupId, PlatformAdminApi, Plugin, PluginContext, PluginMetadata, PluginResources,
    RoleId, User, UserId, UserRoleId,
};
use uuid::Uuid;

junius_sdk::plugin_metadata!();

mod proto {
    //! Generated by `connectrpc-build` (see build.rs): buffa message types plus
    //! the `admin.v1` Connect service traits + registration glue.
    #![allow(
        clippy::all,
        clippy::pedantic,
        missing_docs,
        dead_code,
        unused_qualifications
    )]
    include!(concat!(env!("OUT_DIR"), "/_connectrpc.rs"));
}

include!(concat!(env!("OUT_DIR"), "/_rpc_requires.rs"));

use proto::admin::v1 as pb;
use proto::admin::v1::{
    AuditService, AuditServiceExt, GroupAdminService, GroupAdminServiceExt,
    OidcMappingAdminService, OidcMappingAdminServiceExt, OwnedAddGroupMemberRequestView,
    OwnedAssignUserRoleRequestView, OwnedAuditServiceListRequestView, OwnedCreateGroupRequestView,
    OwnedCreateGroupRoleRequestView, OwnedCreateOidcMappingRequestView,
    OwnedCreateUserRoleRequestView, OwnedDeleteGroupRequestView, OwnedDeleteGroupRoleRequestView,
    OwnedDeleteOidcMappingRequestView, OwnedDeleteUserRoleRequestView,
    OwnedFindUserByEmailRequestView, OwnedListGroupMembersRequestView,
    OwnedListGroupRolesRequestView, OwnedListGroupsRequestView, OwnedListOidcMappingsRequestView,
    OwnedListPermissionsRequestView, OwnedListUserRoleAssignmentsRequestView,
    OwnedListUserRolesRequestView, OwnedRemoveGroupMemberRequestView,
    OwnedRevokeUserRoleRequestView, OwnedSetGroupRolePermissionsRequestView,
    OwnedSetUserRolePermissionsRequestView, OwnedUpdateGroupRequestView, PermissionCatalogService,
    PermissionCatalogServiceExt, UserAdminService, UserAdminServiceExt, UserRoleAdminService,
    UserRoleAdminServiceExt,
};

/// Per-request state for the admin plugin. The plugin holds no typed repos —
/// every mutation flows through `PluginResources::platform_admin` — so the
/// struct is empty save for the permission-witness phantom. `#[derive(PluginCtx)]`
/// only accepts `#[repo]` fields, so we hand-implement [`Clone`] +
/// [`BuildState`] here; the `AdminCtx<P>` alias gives handlers the same
/// extractor ergonomics as the macro-generated form.
pub struct AdminState<P = ()> {
    _phantom: std::marker::PhantomData<P>,
}

impl<P> Clone for AdminState<P> {
    fn clone(&self) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

impl<P> BuildState for AdminState<P> {
    fn build(_resources: &PluginResources, _user: Option<&User>) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

pub type AdminCtx<P> = PluginContext<AdminState<P>, P>;

pub struct AdminPlugin;

impl AdminPlugin {
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl Default for AdminPlugin {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Plugin for AdminPlugin {
    fn metadata(&self) -> &'static PluginMetadata {
        &METADATA
    }

    fn routes(&self) -> Router {
        Router::new().route("/ping", get(|| async { "pong" }))
    }

    fn register_rpc(&self, router: connectrpc::Router) -> connectrpc::Router {
        let router = Arc::new(GroupAdminRpc).register(router);
        let router = Arc::new(UserRoleAdminRpc).register(router);
        let router = Arc::new(UserAdminRpc).register(router);
        let router = Arc::new(OidcMappingAdminRpc).register(router);
        let router = Arc::new(PermissionCatalogRpc).register(router);
        Arc::new(AuditRpc).register(router)
    }
}

// =============================================================================
// GroupAdminService
// =============================================================================

struct GroupAdminRpc;

#[junius_sdk::rpc_service(GroupAdminService)]
impl GroupAdminRpc {
    async fn list_groups(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::ListGroups>,
        _request: OwnedListGroupsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListGroupsResponse>> {
        let groups = admin(&actx).list_groups().await?;
        Ok(Response::new(pb::ListGroupsResponse {
            groups: groups
                .into_iter()
                .map(|g| pb::Group {
                    id: g.id.to_string(),
                    name: g.name,
                    description: g.description.unwrap_or_default(),
                    ..Default::default()
                })
                .collect(),
            ..Default::default()
        }))
    }

    async fn create_group(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::CreateGroup>,
        request: OwnedCreateGroupRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateGroupResponse>> {
        let name = require_nonempty(request.name, "name")?;
        let description = optional(request.description);
        let created = admin(&actx)
            .create_group(&name, description.as_deref())
            .await?;
        Ok(Response::new(pb::CreateGroupResponse {
            group: Some(pb::Group {
                id: created.id.to_string(),
                name: created.name,
                description: created.description.unwrap_or_default(),
                ..Default::default()
            })
            .into(),
            ..Default::default()
        }))
    }

    async fn update_group(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::UpdateGroup>,
        request: OwnedUpdateGroupRequestView,
    ) -> ServiceResult<impl Encodable<pb::UpdateGroupResponse>> {
        let id = GroupId(parse_uuid(request.id, "id")?);
        admin(&actx)
            .update_group(
                id,
                non_empty_str(request.name),
                non_empty_str(request.description),
            )
            .await?;
        Ok(Response::new(pb::UpdateGroupResponse::default()))
    }

    async fn delete_group(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::DeleteGroup>,
        request: OwnedDeleteGroupRequestView,
    ) -> ServiceResult<impl Encodable<pb::DeleteGroupResponse>> {
        let id = GroupId(parse_uuid(request.id, "id")?);
        admin(&actx).delete_group(id).await?;
        Ok(Response::new(pb::DeleteGroupResponse::default()))
    }

    async fn list_group_roles(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::ListGroupRoles>,
        request: OwnedListGroupRolesRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListGroupRolesResponse>> {
        let group = GroupId(parse_uuid(request.group_id, "group_id")?);
        let roles = admin(&actx).list_group_roles(group).await?;
        Ok(Response::new(pb::ListGroupRolesResponse {
            roles: roles
                .into_iter()
                .map(|r| pb::GroupRole {
                    id: r.id.to_string(),
                    group_id: r.group_id.to_string(),
                    name: r.name,
                    permissions: r.permissions,
                    ..Default::default()
                })
                .collect(),
            ..Default::default()
        }))
    }

    async fn create_group_role(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::CreateGroupRole>,
        request: OwnedCreateGroupRoleRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateGroupRoleResponse>> {
        let group = GroupId(parse_uuid(request.group_id, "group_id")?);
        let name = require_nonempty(request.name, "name")?;
        let created = admin(&actx).create_group_role(group, &name).await?;
        Ok(Response::new(pb::CreateGroupRoleResponse {
            role: Some(pb::GroupRole {
                id: created.id.to_string(),
                group_id: created.group_id.to_string(),
                name: created.name,
                permissions: created.permissions,
                ..Default::default()
            })
            .into(),
            ..Default::default()
        }))
    }

    async fn delete_group_role(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::DeleteGroupRole>,
        request: OwnedDeleteGroupRoleRequestView,
    ) -> ServiceResult<impl Encodable<pb::DeleteGroupRoleResponse>> {
        let role = RoleId(parse_uuid(request.role_id, "role_id")?);
        admin(&actx).delete_group_role(role).await?;
        Ok(Response::new(pb::DeleteGroupRoleResponse::default()))
    }

    async fn set_group_role_permissions(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::SetGroupRolePermissions>,
        request: OwnedSetGroupRolePermissionsRequestView,
    ) -> ServiceResult<impl Encodable<pb::SetGroupRolePermissionsResponse>> {
        let role = RoleId(parse_uuid(request.role_id, "role_id")?);
        let perms: Vec<String> = request
            .permissions
            .iter()
            .map(ToString::to_string)
            .collect();
        admin(&actx)
            .set_group_role_permissions(role, &perms)
            .await?;
        Ok(Response::new(pb::SetGroupRolePermissionsResponse::default()))
    }

    async fn list_group_members(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::ListGroupMembers>,
        request: OwnedListGroupMembersRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListGroupMembersResponse>> {
        let group = GroupId(parse_uuid(request.group_id, "group_id")?);
        let members = admin(&actx).list_group_members(group).await?;
        Ok(Response::new(pb::ListGroupMembersResponse {
            members: members
                .into_iter()
                .map(|m| pb::Membership {
                    user_id: m.user_id.to_string(),
                    email: m.email,
                    display_name: m.display_name,
                    role_id: m.role_id.to_string(),
                    role_name: m.role_name,
                    managed_by: m.managed_by,
                    managed_source: m.managed_source.unwrap_or_default(),
                    ..Default::default()
                })
                .collect(),
            ..Default::default()
        }))
    }

    async fn add_group_member(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::AddGroupMember>,
        request: OwnedAddGroupMemberRequestView,
    ) -> ServiceResult<impl Encodable<pb::AddGroupMemberResponse>> {
        let group = GroupId(parse_uuid(request.group_id, "group_id")?);
        let user = UserId(parse_uuid(request.user_id, "user_id")?);
        let role = RoleId(parse_uuid(request.role_id, "role_id")?);
        admin(&actx).add_group_member(group, user, role).await?;
        Ok(Response::new(pb::AddGroupMemberResponse::default()))
    }

    async fn remove_group_member(
        &self,
        actx: AdminCtx<crate::__rpc_requires::group_admin_service::RemoveGroupMember>,
        request: OwnedRemoveGroupMemberRequestView,
    ) -> ServiceResult<impl Encodable<pb::RemoveGroupMemberResponse>> {
        let group = GroupId(parse_uuid(request.group_id, "group_id")?);
        let user = UserId(parse_uuid(request.user_id, "user_id")?);
        admin(&actx).remove_group_member(group, user).await?;
        Ok(Response::new(pb::RemoveGroupMemberResponse::default()))
    }
}

// =============================================================================
// UserRoleAdminService
// =============================================================================

struct UserRoleAdminRpc;

#[junius_sdk::rpc_service(UserRoleAdminService)]
impl UserRoleAdminRpc {
    async fn list_user_roles(
        &self,
        actx: AdminCtx<crate::__rpc_requires::user_role_admin_service::ListUserRoles>,
        _request: OwnedListUserRolesRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListUserRolesResponse>> {
        let roles = admin(&actx).list_user_roles().await?;
        Ok(Response::new(pb::ListUserRolesResponse {
            roles: roles
                .into_iter()
                .map(|r| pb::UserRole {
                    id: r.id.to_string(),
                    name: r.name,
                    description: r.description.unwrap_or_default(),
                    is_builtin: r.is_builtin,
                    permissions: r.permissions,
                    ..Default::default()
                })
                .collect(),
            ..Default::default()
        }))
    }

    async fn create_user_role(
        &self,
        actx: AdminCtx<crate::__rpc_requires::user_role_admin_service::CreateUserRole>,
        request: OwnedCreateUserRoleRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateUserRoleResponse>> {
        let name = require_nonempty(request.name, "name")?;
        let description = optional(request.description);
        let created = admin(&actx)
            .create_user_role(&name, description.as_deref())
            .await?;
        Ok(Response::new(pb::CreateUserRoleResponse {
            role: Some(pb::UserRole {
                id: created.id.to_string(),
                name: created.name,
                description: created.description.unwrap_or_default(),
                is_builtin: created.is_builtin,
                permissions: created.permissions,
                ..Default::default()
            })
            .into(),
            ..Default::default()
        }))
    }

    async fn delete_user_role(
        &self,
        actx: AdminCtx<crate::__rpc_requires::user_role_admin_service::DeleteUserRole>,
        request: OwnedDeleteUserRoleRequestView,
    ) -> ServiceResult<impl Encodable<pb::DeleteUserRoleResponse>> {
        let id = UserRoleId(parse_uuid(request.id, "id")?);
        admin(&actx).delete_user_role(id).await?;
        Ok(Response::new(pb::DeleteUserRoleResponse::default()))
    }

    async fn set_user_role_permissions(
        &self,
        actx: AdminCtx<crate::__rpc_requires::user_role_admin_service::SetUserRolePermissions>,
        request: OwnedSetUserRolePermissionsRequestView,
    ) -> ServiceResult<impl Encodable<pb::SetUserRolePermissionsResponse>> {
        let role = UserRoleId(parse_uuid(request.role_id, "role_id")?);
        let perms: Vec<String> = request
            .permissions
            .iter()
            .map(ToString::to_string)
            .collect();
        admin(&actx).set_user_role_permissions(role, &perms).await?;
        Ok(Response::new(pb::SetUserRolePermissionsResponse::default()))
    }

    async fn list_user_role_assignments(
        &self,
        actx: AdminCtx<crate::__rpc_requires::user_role_admin_service::ListUserRoleAssignments>,
        _request: OwnedListUserRoleAssignmentsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListUserRoleAssignmentsResponse>> {
        let rows = admin(&actx).list_user_role_assignments().await?;
        Ok(Response::new(pb::ListUserRoleAssignmentsResponse {
            assignments: rows
                .into_iter()
                .map(|a| pb::UserRoleAssignment {
                    user_id: a.user_id.to_string(),
                    email: a.email,
                    display_name: a.display_name,
                    role_id: a.role_id.to_string(),
                    role_name: a.role_name,
                    ..Default::default()
                })
                .collect(),
            ..Default::default()
        }))
    }

    async fn assign_user_role(
        &self,
        actx: AdminCtx<crate::__rpc_requires::user_role_admin_service::AssignUserRole>,
        request: OwnedAssignUserRoleRequestView,
    ) -> ServiceResult<impl Encodable<pb::AssignUserRoleResponse>> {
        let user = UserId(parse_uuid(request.user_id, "user_id")?);
        let role = UserRoleId(parse_uuid(request.role_id, "role_id")?);
        admin(&actx).assign_user_role(user, role).await?;
        Ok(Response::new(pb::AssignUserRoleResponse::default()))
    }

    async fn revoke_user_role(
        &self,
        actx: AdminCtx<crate::__rpc_requires::user_role_admin_service::RevokeUserRole>,
        request: OwnedRevokeUserRoleRequestView,
    ) -> ServiceResult<impl Encodable<pb::RevokeUserRoleResponse>> {
        let user = UserId(parse_uuid(request.user_id, "user_id")?);
        let role = UserRoleId(parse_uuid(request.role_id, "role_id")?);
        admin(&actx).revoke_user_role(user, role).await?;
        Ok(Response::new(pb::RevokeUserRoleResponse::default()))
    }
}

// =============================================================================
// PermissionCatalogService
// =============================================================================

struct PermissionCatalogRpc;

#[junius_sdk::rpc_service(PermissionCatalogService)]
impl PermissionCatalogRpc {
    async fn list_permissions(
        &self,
        actx: AdminCtx<crate::__rpc_requires::permission_catalog_service::ListPermissions>,
        _request: OwnedListPermissionsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListPermissionsResponse>> {
        let catalogue = admin(&actx).permission_catalogue()?;
        Ok(Response::new(pb::ListPermissionsResponse {
            plugins: catalogue
                .iter()
                .map(|p| pb::PluginPermissions {
                    plugin: p.plugin.clone(),
                    display_name: p.display_name.clone(),
                    permissions: p
                        .permissions
                        .iter()
                        .map(|e| pb::PermissionEntry {
                            name: e.name.clone(),
                            description: e.description.clone(),
                            ..Default::default()
                        })
                        .collect(),
                    ..Default::default()
                })
                .collect(),
            ..Default::default()
        }))
    }
}

// =============================================================================
// UserAdminService
// =============================================================================

struct UserAdminRpc;

#[junius_sdk::rpc_service(UserAdminService)]
impl UserAdminRpc {
    async fn find_user_by_email(
        &self,
        actx: AdminCtx<crate::__rpc_requires::user_admin_service::FindUserByEmail>,
        request: OwnedFindUserByEmailRequestView,
    ) -> ServiceResult<impl Encodable<pb::FindUserByEmailResponse>> {
        let email = require_nonempty(request.email, "email")?;
        let id = admin(&actx).find_user_by_email(&email).await?;
        let (user_id, display_name) = match id {
            Some(uid) => {
                // The admin API's display-name lookup goes through the public
                // users handle so we get the email-display pair in one shot.
                let display = actx
                    .resources
                    .users
                    .lookup(uid)
                    .await?
                    .map(|u| u.display_name)
                    .unwrap_or_default();
                (uid.to_string(), display)
            }
            None => (String::new(), String::new()),
        };
        Ok(Response::new(pb::FindUserByEmailResponse {
            user_id,
            display_name,
            ..Default::default()
        }))
    }
}

// =============================================================================
// OidcMappingAdminService
// =============================================================================

struct OidcMappingAdminRpc;

#[junius_sdk::rpc_service(OidcMappingAdminService)]
impl OidcMappingAdminRpc {
    async fn list_oidc_mappings(
        &self,
        actx: AdminCtx<crate::__rpc_requires::oidc_mapping_admin_service::ListOidcMappings>,
        _request: OwnedListOidcMappingsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListOidcMappingsResponse>> {
        let rows = admin(&actx).list_oidc_mappings().await?;
        Ok(Response::new(pb::ListOidcMappingsResponse {
            mappings: rows
                .into_iter()
                .map(|m| pb::OidcMapping {
                    id: m.id.to_string(),
                    oidc_group_name: m.oidc_group_name,
                    group_id: m.group_id.to_string(),
                    group_name: m.group_name,
                    role_id: m.role_id.to_string(),
                    role_name: m.role_name,
                    ..Default::default()
                })
                .collect(),
            ..Default::default()
        }))
    }

    async fn create_oidc_mapping(
        &self,
        actx: AdminCtx<crate::__rpc_requires::oidc_mapping_admin_service::CreateOidcMapping>,
        request: OwnedCreateOidcMappingRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateOidcMappingResponse>> {
        let oidc_group_name = require_nonempty(request.oidc_group_name, "oidc_group_name")?;
        let group = GroupId(parse_uuid(request.group_id, "group_id")?);
        let role = RoleId(parse_uuid(request.role_id, "role_id")?);
        let id = admin(&actx)
            .create_oidc_mapping(&oidc_group_name, group, role)
            .await?;
        Ok(Response::new(pb::CreateOidcMappingResponse {
            id: id.to_string(),
            ..Default::default()
        }))
    }

    async fn delete_oidc_mapping(
        &self,
        actx: AdminCtx<crate::__rpc_requires::oidc_mapping_admin_service::DeleteOidcMapping>,
        request: OwnedDeleteOidcMappingRequestView,
    ) -> ServiceResult<impl Encodable<pb::DeleteOidcMappingResponse>> {
        let id = parse_uuid(request.id, "id")?;
        admin(&actx).delete_oidc_mapping(id).await?;
        Ok(Response::new(pb::DeleteOidcMappingResponse::default()))
    }
}

// =============================================================================
// AuditService
// =============================================================================

struct AuditRpc;

#[junius_sdk::rpc_service(AuditService)]
impl AuditRpc {
    async fn list(
        &self,
        actx: AdminCtx<crate::__rpc_requires::audit_service::List>,
        request: OwnedAuditServiceListRequestView,
    ) -> ServiceResult<impl Encodable<pb::AuditServiceListResponse>> {
        let actor_user_id = parse_optional_uuid(request.actor_user_id.unwrap_or_default())?;
        let resource_kind: Option<&str> = request.resource_kind.and_then(|s| non_empty_str(s));
        let event_kind: Option<&str> = request.event_kind.and_then(|s| non_empty_str(s));
        let starts_at = parse_optional_rfc3339(request.starts_at.unwrap_or_default())?;
        let ends_at = parse_optional_rfc3339(request.ends_at.unwrap_or_default())?;
        let cursor = decode_cursor(request.cursor.unwrap_or_default())?;
        let limit = if request.limit == 0 {
            50
        } else {
            request.limit
        };

        let filter = junius_sdk::AuditFilter {
            actor_user_id,
            resource_kind,
            event_kind,
            starts_at,
            ends_at,
        };

        let page = admin(&actx)
            .list_audit_events(&filter, cursor.as_ref(), limit)
            .await?;

        Ok(Response::new(pb::AuditServiceListResponse {
            events: page
                .events
                .into_iter()
                .map(|e| pb::AuditEvent {
                    id: e.id.to_string(),
                    event_kind: e.event_kind,
                    actor_user_id: e.actor_user_id.map_or_else(String::new, |u| u.to_string()),
                    actor_email: e.actor_email.unwrap_or_default(),
                    actor_display_name: e.actor_display_name.unwrap_or_default(),
                    resource_kind: e.resource_kind.unwrap_or_default(),
                    resource_id: e.resource_id.map_or_else(String::new, |u| u.to_string()),
                    details: serde_json::to_string(&e.details).unwrap_or_default(),
                    occurred_at: e.occurred_at.to_rfc3339(),
                    ..Default::default()
                })
                .collect(),
            next_cursor: page.next_cursor.map(|c| encode_cursor(&c)),
            ..Default::default()
        }))
    }
}

fn parse_optional_uuid(s: &str) -> Result<Option<Uuid>, ConnectError> {
    if s.is_empty() {
        return Ok(None);
    }
    Uuid::parse_str(s)
        .map(Some)
        .map_err(|_| invalid_field("actor_user_id"))
}

fn parse_optional_rfc3339(s: &str) -> Result<Option<chrono::DateTime<chrono::Utc>>, ConnectError> {
    if s.is_empty() {
        return Ok(None);
    }
    chrono::DateTime::parse_from_rfc3339(s)
        .map(|dt| Some(dt.with_timezone(&chrono::Utc)))
        .map_err(|_| invalid_field("date (RFC3339)"))
}

fn encode_cursor(c: &junius_sdk::AuditCursor) -> String {
    use base64::Engine as _;
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    let raw = format!("{}|{}", c.occurred_at.to_rfc3339(), c.id);
    URL_SAFE_NO_PAD.encode(raw.as_bytes())
}

fn decode_cursor(s: &str) -> Result<Option<junius_sdk::AuditCursor>, ConnectError> {
    use base64::Engine as _;
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    if s.is_empty() {
        return Ok(None);
    }
    let bytes = URL_SAFE_NO_PAD
        .decode(s)
        .map_err(|_| ConnectError::invalid_argument("admin.error.invalid_cursor"))?;
    let text = String::from_utf8(bytes)
        .map_err(|_| ConnectError::invalid_argument("admin.error.invalid_cursor"))?;
    let (ts_str, id_str) = text
        .split_once('|')
        .ok_or_else(|| ConnectError::invalid_argument("admin.error.invalid_cursor"))?;
    let occurred_at = chrono::DateTime::parse_from_rfc3339(ts_str)
        .map(|dt| dt.with_timezone(&chrono::Utc))
        .map_err(|_| ConnectError::invalid_argument("admin.error.invalid_cursor"))?;
    let id = Uuid::parse_str(id_str)
        .map_err(|_| ConnectError::invalid_argument("admin.error.invalid_cursor"))?;
    Ok(Some(junius_sdk::AuditCursor { occurred_at, id }))
}

// =============================================================================
// Helpers
// =============================================================================

/// Shortcut for grabbing the typed admin API off the per-request context.
fn admin<P>(ctx: &PluginContext<AdminState<P>, P>) -> &PlatformAdminApi {
    &ctx.resources.platform_admin
}

fn parse_uuid(value: &str, field: &str) -> Result<Uuid, ConnectError> {
    Uuid::parse_str(value).map_err(|_| invalid_field(field))
}

fn require_nonempty(value: &str, field: &str) -> Result<String, ConnectError> {
    if value.trim().is_empty() {
        Err(required_field(field))
    } else {
        Ok(value.to_string())
    }
}

fn optional(value: &str) -> Option<String> {
    if value.is_empty() {
        None
    } else {
        Some(value.to_string())
    }
}

/// Empty proto string → `None`; anything else → `Some(&str)`. Used for
/// partial-update RPCs that pass-through unchanged fields.
fn non_empty_str(value: &str) -> Option<&str> {
    if value.is_empty() { None } else { Some(value) }
}

fn invalid_field(field: &str) -> ConnectError {
    ConnectError::invalid_argument(format!("admin.error.field_invalid:{field}"))
}

fn required_field(field: &str) -> ConnectError {
    ConnectError::invalid_argument(format!("admin.error.field_required:{field}"))
}
