//! `hello` — the smoke-test plugin. M03 introduced the HTTP-only shape
//! (`GET /ping → "pong"`). M05 added a Connect-RPC `Greet`. M06.5 re-platforms
//! the RPC onto `connectrpc` (Anthropic's Tower-based Connect server) with
//! `buffa` message types, replacing the M05 hand-rolled unary server: the
//! service is now a generated trait, and the host mounts it as an axum router.

use std::sync::Arc;

use async_trait::async_trait;
use axum::{Router, routing::get};
use connectrpc::{Encodable, RequestContext, Response, ServiceResult};
use junius_sdk::{Plugin, PluginMetadata};

junius_sdk::plugin_metadata!();

mod proto {
    //! Generated by `connectrpc-build` (see build.rs): buffa message types plus
    //! the `HelloService` Connect trait + registration glue.
    #![allow(
        clippy::all,
        clippy::pedantic,
        missing_docs,
        dead_code,
        unused_qualifications
    )]
    include!(concat!(env!("OUT_DIR"), "/_connectrpc.rs"));
}

use proto::hello::v1::{HelloService, HelloServiceExt, OwnedGreetRequestView};
// Wire message types, re-exported for tests and any in-process callers.
pub use proto::hello::v1::{GreetRequest, GreetResponse};

pub struct HelloPlugin;

impl HelloPlugin {
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl Default for HelloPlugin {
    fn default() -> Self {
        Self::new()
    }
}

/// Connect-RPC implementation of `hello.v1.HelloService`. Stateless for now;
/// once M07 lands repositories, `Greet` would route through one (reading the
/// caller + plugin resources from `ctx.extensions()`).
struct HelloRpc;

impl HelloService for HelloRpc {
    async fn greet(
        &self,
        _ctx: RequestContext,
        request: OwnedGreetRequestView,
    ) -> ServiceResult<impl Encodable<GreetResponse>> {
        let name = if request.name.is_empty() {
            "world"
        } else {
            request.name
        };
        Ok(Response::new(GreetResponse {
            message: format!("Hello, {name}!"),
            ..Default::default()
        }))
    }
}

#[async_trait]
impl Plugin for HelloPlugin {
    fn metadata(&self) -> &'static PluginMetadata {
        &METADATA
    }

    fn routes(&self) -> Router {
        Router::new().route("/ping", get(|| async { "pong" }))
    }

    fn rpc_routes(&self) -> Router {
        Arc::new(HelloRpc)
            .register(connectrpc::Router::new())
            .into_axum_router()
    }
}
