//! `hello` — the smoke-test plugin. M03 introduced the HTTP-only shape
//! (`GET /ping → "pong"`). M05 added a Connect-RPC `Greet`. M06.5 re-platforms
//! the RPC onto `connectrpc` (Anthropic's Tower-based Connect server) with
//! `buffa` message types, replacing the M05 hand-rolled unary server: the
//! service is now a generated trait, and the host mounts it as an axum router.

use std::sync::Arc;

use async_trait::async_trait;
use axum::{Json, Router, routing::get};
use connectrpc::{Encodable, RequestContext, Response, ServiceResult};
use junius_sdk::{ApiError, Plugin, PluginContext, PluginCtx, PluginMetadata};

junius_sdk::plugin_metadata!();

mod proto {
    //! Generated by `connectrpc-build` (see build.rs): buffa message types plus
    //! the `HelloService` Connect trait + registration glue.
    #![allow(
        clippy::all,
        clippy::pedantic,
        missing_docs,
        dead_code,
        unused_qualifications
    )]
    include!(concat!(env!("OUT_DIR"), "/_connectrpc.rs"));
}

pub mod repo;

use proto::hello::v1 as pb;
use proto::hello::v1::{
    HelloService, HelloServiceExt, OwnedCreateGreetingRequestView, OwnedGreetRequestView,
    OwnedListGreetingsRequestView,
};
// Wire message types, re-exported for tests and any in-process callers.
pub use proto::hello::v1::{GreetRequest, GreetResponse};

use crate::permissions::{HelloRead, HelloWrite};
use crate::repo::{Greeting, HelloRepo, NewGreeting};

/// Convert a stored greeting into its proto wire form.
fn greeting_to_proto(g: Greeting) -> pb::Greeting {
    pb::Greeting {
        id: g.id.0.to_string(),
        name: g.name,
        body: g.body,
        created: g.created.to_rfc3339(),
        ..Default::default()
    }
}

/// Per-request state for the hello plugin: its repositories, typed on the
/// permission witness `P`. `#[derive(PluginCtx)]` generates the extractor for
/// `HelloCtx<P>`.
#[derive(PluginCtx)]
pub struct HelloState<P = ()> {
    #[repo]
    pub greetings: HelloRepo<P>,
}

/// The hello plugin's request context: state + caller + resources, proven to
/// hold the permissions in `P`.
pub type HelloCtx<P = ()> = PluginContext<HelloState<P>, P>;

/// `GET /h/hello/greetings` — list greetings. Requires `hello:read`, enforced by
/// extracting `HelloCtx<permissions!(HelloRead)>`.
async fn list_greetings(
    ctx: HelloCtx<junius_sdk::permissions!(HelloRead)>,
) -> Result<Json<Vec<Greeting>>, ApiError> {
    Ok(Json(ctx.state.greetings.list().await?))
}

pub struct HelloPlugin;

impl HelloPlugin {
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl Default for HelloPlugin {
    fn default() -> Self {
        Self::new()
    }
}

/// Connect-RPC implementation of `hello.v1.HelloService`. `Greet` is permission-
/// free; the CRUD methods build a typed `HelloCtx<P>` from the request context
/// (`from_rpc`), which re-checks the witness and yields the permission-gated
/// repository. The host's RPC guard also enforces each method's
/// `(platform.v1.requires)` before the handler runs.
struct HelloRpc;

impl HelloService for HelloRpc {
    async fn greet(
        &self,
        _ctx: RequestContext,
        request: OwnedGreetRequestView,
    ) -> ServiceResult<impl Encodable<GreetResponse>> {
        let name = if request.name.is_empty() {
            "world"
        } else {
            request.name
        };
        Ok(Response::new(GreetResponse {
            message: format!("Hello, {name}!"),
            ..Default::default()
        }))
    }

    async fn list_greetings(
        &self,
        ctx: RequestContext,
        _request: OwnedListGreetingsRequestView,
    ) -> ServiceResult<impl Encodable<pb::ListGreetingsResponse>> {
        let hctx = HelloCtx::<junius_sdk::permissions!(HelloRead)>::from_rpc(&ctx)?;
        let greetings = hctx.state.greetings.list().await?;
        Ok(Response::new(pb::ListGreetingsResponse {
            greetings: greetings.into_iter().map(greeting_to_proto).collect(),
            ..Default::default()
        }))
    }

    async fn create_greeting(
        &self,
        ctx: RequestContext,
        request: OwnedCreateGreetingRequestView,
    ) -> ServiceResult<impl Encodable<pb::CreateGreetingResponse>> {
        let hctx = HelloCtx::<junius_sdk::permissions!(HelloRead & HelloWrite)>::from_rpc(&ctx)?;
        let created = hctx
            .state
            .greetings
            .create(NewGreeting {
                name: request.name.to_string(),
                body: request.body.to_string(),
            })
            .await?;
        Ok(Response::new(pb::CreateGreetingResponse {
            greeting: Some(greeting_to_proto(created)).into(),
            ..Default::default()
        }))
    }
}

#[async_trait]
impl Plugin for HelloPlugin {
    fn metadata(&self) -> &'static PluginMetadata {
        &METADATA
    }

    fn routes(&self) -> Router {
        Router::new()
            .route("/ping", get(|| async { "pong" }))
            .route("/greetings", get(list_greetings))
    }

    fn rpc_routes(&self) -> Router {
        Arc::new(HelloRpc)
            .register(connectrpc::Router::new())
            .into_axum_router()
    }
}
