//! `platform.lock` — the resolved-source lockfile a deployment commits next to
//! its `platform.toml`. `junius build` writes it (recording the resolved git rev
//! and blake3 content hashes of the source tree and each enabled plugin) and, on
//! later builds, fails if the resolved source no longer matches — unless run with
//! `--update-lock`. This type is pure (de)serialization; the hashing lives in the
//! CLI so the manifest crate stays free of `blake3`.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::error::ManifestError;

/// The contents of `platform.lock`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeploymentLock {
    pub source: LockSource,
    /// Enabled plugin name → `"blake3:<hex>"` of that plugin's subtree.
    #[serde(default)]
    pub plugins: BTreeMap<String, String>,
}

/// The resolved source the lock pins.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockSource {
    /// The git URL (`git+…`) or local path the deployment's `[source]` named.
    pub url_or_path: String,
    /// The resolved commit SHA (git sources only; `None` for `path`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolved_rev: Option<String>,
    /// `"blake3:<hex>"` of the whole resolved source tree.
    pub content_hash: String,
}

impl DeploymentLock {
    /// Parse a `platform.lock`.
    pub fn parse(src: &str) -> Result<Self, ManifestError> {
        Ok(toml::from_str(src)?)
    }

    /// Render to TOML with the generated-file header.
    #[must_use]
    #[allow(
        clippy::expect_used,
        reason = "DeploymentLock is plain data (strings + a string map); TOML serialization cannot fail"
    )]
    pub fn to_toml_string(&self) -> String {
        let body = toml::to_string_pretty(self).expect("DeploymentLock serializes to TOML");
        format!("# Generated by junius — do not edit.\n\n{body}")
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, reason = "tests panic on unexpected failures")]
mod tests {
    use super::*;

    fn sample() -> DeploymentLock {
        DeploymentLock {
            source: LockSource {
                url_or_path: "git+https://example.test/junius.git".to_string(),
                resolved_rev: Some("a".repeat(40)),
                content_hash: "blake3:deadbeef".to_string(),
            },
            plugins: BTreeMap::from([
                ("hello".to_string(), "blake3:1111".to_string()),
                ("widgets".to_string(), "blake3:2222".to_string()),
            ]),
        }
    }

    #[test]
    fn round_trips() {
        let lock = sample();
        let rendered = lock.to_toml_string();
        assert!(rendered.starts_with("# Generated by junius — do not edit.\n"));
        assert_eq!(DeploymentLock::parse(&rendered).unwrap(), lock);
    }

    #[test]
    fn path_source_omits_resolved_rev() {
        let lock = DeploymentLock {
            source: LockSource {
                url_or_path: "../..".to_string(),
                resolved_rev: None,
                content_hash: "blake3:abc".to_string(),
            },
            plugins: BTreeMap::new(),
        };
        let rendered = lock.to_toml_string();
        assert!(!rendered.contains("resolved_rev"));
        assert_eq!(DeploymentLock::parse(&rendered).unwrap(), lock);
    }

    #[test]
    fn parses_without_plugins_table() {
        let lock = DeploymentLock::parse(
            "[source]\nurl_or_path = \"../..\"\ncontent_hash = \"blake3:x\"\n",
        )
        .unwrap();
        assert!(lock.plugins.is_empty());
        assert_eq!(lock.source.resolved_rev, None);
    }
}
